dataloader_args:
  batch_size: 4 #RTX2080 1, V100: 8, A800: 16
  drop_last: true
  num_workers: 12
  pin_memory: true
  prefetch_factor: 6

dataset_args:
  resample_rate: &sr 16000
  sample_num_per_epoch: 0
  shuffle: False
  shuffle_args:
    shuffle_size: 2500
  whole_utt: True
  chunk_len: 48000
  noise_prob: 0 # noqa
  noise_lmdb_file: './data/musan/lmdb'
  cues:
    spatial:
      use: true
      required: true
  cue_processing:
    spatial:

enable_amp: false
exp_dir: exp/BSRNN
gpus: '0,1'
log_batch_interval: 100

loss: SISDR
loss_args: { }

# loss: [SISDR, XX]               ### Put SISDR in the first position for validation set
# loss_args:
#   loss_posi: [[0],[1]]
#   loss_weight: [[1.0],[1.0]]

model:
  tse_model: TSE_BSRNN_SPATIAL
model_args:
  tse_model:        
    win: 512
    stride: 128  
    separator:
      sr: 16000
      feature_dim: 128
      num_repeat: 6
      causal: False
      nspk: 1
    spatial:
      geometry:
        fs: 16000
        c: 343.0
        mic_spacing: 0.03333333 

      pairs:
        - [0, 1]
        - [1, 2]
        - [2, 3]
        - [0, 3]
      mic_coords:
        - [-0.05,        0.0, 0.0]  # Mic 0 (最左)
        - [-0.0166,  0.0, 0.0]  # Mic 1
        - [ 0.0166,  0.0, 0.0]  # Mic 2
        - [ 0.05,        0.0, 0.0]  # Mic 3 (最右)
      features:
        ipd: 
          enabled: True        
        cdf: 
          enabled: True        
        sdf: 
          enabled: True        
        delta_stft: 
          enabled: True

model_init:
  tse_model: null
  discriminator: null
  spk_model: null

num_avg: 10
num_epochs: 150

optimizer:
  tse_model: Adam
optimizer_args:
  tse_model:
    lr: 0.001  # NOTICE: These args do NOT work! The initial lr is determined in the scheduler_args currently!
    weight_decay: 0.0001

clip_grad: 5.0
save_epoch_interval: 1

scheduler:
  tse_model: ExponentialDecrease
scheduler_args:
  tse_model:
    final_lr: 2.5e-05
    initial_lr: 0.001
    warm_from_zero: false
    warm_up_epoch: 0

seed: 42
