dataloader_args:
  batch_size: 2 #RTX2080 1, V100: 8, A800: 16
  drop_last: true
  num_workers: 6
  pin_memory: true
  prefetch_factor: 6

dataset_args:
  resample_rate: &sr 16000
  sample_num_per_epoch: 0
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  chunk_len: 48000
  noise_prob: 0 # prob to add noise aug per sample
  noise_lmdb_file: './data/musan/lmdb'
  cues:
    audio:
      use: true
      required: true
  cue_processing:
    audio:
      reverb_enroll_prob: 0
      noise_enroll_prob: 0

enable_amp: false
exp_dir: exp/BSRNN
gpus: '0,1'
log_batch_interval: 100

loss: SISDR
loss_args: { }

# loss: [SISDR, XX]               ### Put SISDR in the first position for validation set
# loss_args:
#   loss_posi: [[0],[1]]
#   loss_weight: [[1.0],[1.0]]

model:
  tse_model: TSE_BSRNN_SPK
model_args:
  tse_model:
    separator:
      sr: *sr
      win: 512
      stride: 128
      feature_dim: 128
      num_repeat: 6
      causal: False
      nspk: 1
    speaker:
      features:
        listen:
          enabled: False
          glue: 512
        usef:
          enabled: True
          spec_dim: 2
          approx_qk_dim: 512
          n_head: 4
          t_ksize: 3
        tfmap:
          enabled: False
          type: "spec"   # 'spec'
        context:
          enabled: True
          speaker_model:
          embed_dim: 512     # Need check the speaker encoder in wespeaker
          atten_dim: 128         # dim in cross-attention
          num_heads: 2
          fusion": "multiply"    # add | concat | multiply
        spkemb:
          enabled: False
          speaker_model:
          fusion: "multiply" # add | concat | multiply
      speaker_model:
        fbank:
          num_mel_bins: 80
          frame_shift: 10
          frame_length: 25
          dither: 1.0
          sample_rate: *sr       # sampling rate
        # ---- Speaker Encoder
        speaker_encoder:
          model: ECAPA_TDNN_GLOB_c512
          pretrained: ./wespeaker_models/voxceleb_ECAPA512/avg_model.pt
          spk_args:
            embed_dim: 192         # speaker embedding
            feat_dim: 80         # num_mel_bins
            pooling_func: "ASTP"
          ####### ResNet    The pretrained speaker encoders are available from: https://github.com/wenet-e2e/wespeaker/blob/master/docs/pretrained.md
          # spk_model: ResNet34 # ResNet18, ResNet34, ResNet50, ResNet101, ResNet152
          # spk_model_init: False #./wespeaker_models/voxceleb_resnet34/avg_model.pt
          # spk_args:
          #   feat_dim: 80
          #   embed_dim: &embed_dim 256
          #   pooling_func: "TSTP" # TSTP, ASTP, MQMHASTP
          #   two_emb_layer: False
          ####### CAMPPlus
          # spk_model: CAMPPlus
          # spk_model_init: False
          # spk_args:
          #   feat_dim: 80
          #   embed_dim: &embed_dim 192
          #   pooling_func: "TSTP" # TSTP, ASTP, MQMHASTP
          #################################################################

# find_unused_parameters: True

model_init:
  tse_model: null
  discriminator: null
  spk_model: null

num_avg: 10
num_epochs: 150

optimizer:
  tse_model: Adam
optimizer_args:
  tse_model:
    lr: 0.001  # NOTICE: These args do NOT work! The initial lr is determined in the scheduler_args currently!
    weight_decay: 0.0001

clip_grad: 5.0
save_epoch_interval: 1

scheduler:
  tse_model: ExponentialDecrease
scheduler_args:
  tse_model:
    final_lr: 2.5e-05
    initial_lr: 0.001
    warm_from_zero: false
    warm_up_epoch: 0

seed: 42
